/**
 * Morphect - Multi-Language Code Obfuscator
 *
 * mba_xor.cpp - MBA transformation for XOR operations
 *
 * Mathematical identities:
 *   a ^ b = (a | b) - (a & b)
 *   a ^ b = (a + b) - 2*(a & b)
 *   a ^ b = (a | b) & ~(a & b)
 *   a ^ b = (~a & b) | (a & ~b)
 *   a ^ b = (a | b) & (~a | ~b)
 */

#include "mba_xor.hpp"
#include <regex>
#include <sstream>

namespace morphect {
namespace mba {

bool MBAXor::applyGimple(void* gsi, void* stmt, int variant_idx,
                         const MBAConfig& config) {
    (void)gsi; (void)stmt; (void)variant_idx; (void)config;
    return false;
}

static int g_xor_temp_counter = 300000;

std::vector<std::string> LLVMMBAXor::applyIR(const std::string& line,
                                              int variant_idx,
                                              const MBAConfig& config) {
    std::vector<std::string> result;

    if (!shouldApply(config)) {
        return result;
    }

    // Robust pattern for XOR
    std::regex xor_pattern(
        R"(^(\s*)(%[\w.]+)\s*=\s*xor\s+(<\d+\s*x\s*)?(\w+)(\s*>)?\s+(%[\w.]+),\s*(%[\w.]+|[\d-]+)\s*$)"
    );

    std::smatch match;
    if (!std::regex_match(line, match, xor_pattern)) {
        return result;
    }

    std::string indent = match[1];
    std::string dest = match[2];
    std::string vec_prefix = match[3];
    std::string base_type = match[4];
    std::string vec_suffix = match[5];
    std::string op1 = match[6];
    std::string op2 = match[7];

    std::string type = vec_prefix + base_type + vec_suffix;

    // Skip XOR with -1 (NOT operation) - these are generated by our transforms
    if (op2 == "-1") {
        return result;
    }

    // Skip constant XOR
    if (op1[0] != '%' && op2[0] != '%') {
        return result;
    }

    size_t var_idx = (variant_idx >= 0) ?
        static_cast<size_t>(variant_idx) % 8 : selectVariant(config);

    int base = g_xor_temp_counter;
    g_xor_temp_counter += 10;
    std::string t1 = "%_mba_x" + std::to_string(base);
    std::string t2 = "%_mba_x" + std::to_string(base + 1);
    std::string t3 = "%_mba_x" + std::to_string(base + 2);
    std::string t4 = "%_mba_x" + std::to_string(base + 3);
    std::string t5 = "%_mba_x" + std::to_string(base + 4);

    switch (var_idx) {
        case 0:  // (a | b) - (a & b)
        {
            result.push_back(indent + t1 + " = or " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = and " + type + " " + op1 + ", " + op2);
            result.push_back(indent + dest + " = sub " + type + " " + t1 + ", " + t2);
            break;
        }
        case 1:  // (a + b) - 2 * (a & b)
        {
            result.push_back(indent + t1 + " = add " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = and " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t3 + " = shl " + type + " " + t2 + ", 1");
            result.push_back(indent + dest + " = sub " + type + " " + t1 + ", " + t3);
            break;
        }
        case 2:  // (a | b) & ~(a & b)
        {
            result.push_back(indent + t1 + " = or " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = and " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t3 + " = xor " + type + " " + t2 + ", -1");
            result.push_back(indent + dest + " = and " + type + " " + t1 + ", " + t3);
            break;
        }
        case 3:  // (~a & b) | (a & ~b)
        {
            result.push_back(indent + t1 + " = xor " + type + " " + op1 + ", -1");
            result.push_back(indent + t2 + " = and " + type + " " + t1 + ", " + op2);
            result.push_back(indent + t3 + " = xor " + type + " " + op2 + ", -1");
            result.push_back(indent + t4 + " = and " + type + " " + op1 + ", " + t3);
            result.push_back(indent + dest + " = or " + type + " " + t2 + ", " + t4);
            break;
        }
        case 4:  // (a | b) & (~a | ~b)
        {
            result.push_back(indent + t1 + " = or " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = xor " + type + " " + op1 + ", -1");
            result.push_back(indent + t3 + " = xor " + type + " " + op2 + ", -1");
            result.push_back(indent + t4 + " = or " + type + " " + t2 + ", " + t3);
            result.push_back(indent + dest + " = and " + type + " " + t1 + ", " + t4);
            break;
        }
        case 5:  // (a | b) ^ (a & b) - recursive but different
        {
            result.push_back(indent + t1 + " = or " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = and " + type + " " + op1 + ", " + op2);
            // Expand this XOR differently to avoid infinite recursion
            result.push_back(indent + t3 + " = or " + type + " " + t1 + ", " + t2);
            result.push_back(indent + t4 + " = and " + type + " " + t1 + ", " + t2);
            result.push_back(indent + dest + " = sub " + type + " " + t3 + ", " + t4);
            break;
        }
        case 6:  // (a | b) - (a & b) - simple verified identity
        {
            // a ^ b = (a | b) - (a & b) - same as variant 0 for variety
            result.push_back(indent + t1 + " = or " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = and " + type + " " + op1 + ", " + op2);
            result.push_back(indent + dest + " = sub " + type + " " + t1 + ", " + t2);
            break;
        }
        case 7:  // Complex: (2*(a|b) - (a+b)) - uses relationship between ops
        default:
        {
            result.push_back(indent + t1 + " = or " + type + " " + op1 + ", " + op2);
            result.push_back(indent + t2 + " = shl " + type + " " + t1 + ", 1");
            result.push_back(indent + t3 + " = add " + type + " " + op1 + ", " + op2);
            result.push_back(indent + dest + " = sub " + type + " " + t2 + ", " + t3);
            break;
        }
    }

    logger_.debug("Applied MBA XOR variant {} to: {}", var_idx, line);
    return result;
}

} // namespace mba
} // namespace morphect
